# Changes here will be overwritten by Copier
_commit: v0.2.8
_src_path: git+https://gitlab.ewi.tudelft.nl/reit/python-package-template
coc: our_coc
email: satrya.dewantara@gmail.com
environment_manager: uv
full_name: Satrya Dewantara
host: github.com
license: No license (others may not use, share or modify the code)
min_python_version: '3.10'
org: satryad
project_name: LAHSO
project_short_description: LASHO
python_name: lahso
typing: no_typing
url: https://github.com/satryad/LAHSO
