import gradio as gr

from lahso.ui.model_implementation_tabs import model_implementation_tabs
from lahso.ui.result_comparison_tabs import results_comparison_tabs
from lahso.ui.training_agent_tabs import training_agent_tabs

def main():
    """
    Main function that starts the UI.

    The UI has top-level tabs for different supported functionality.
    """
    print("LAHSO UI starting up...")

    # Each tab is in its own file, and is generated by its own function
    # This was useful at first to create some separation, but seems to not be ideal for
    #  structuring Gradio UIs, since many UI components need to interact with each other
    # If you're going to work on this UI, consider refactoring from functions to some
    #  class-based structure, so you have easy access to different components and
    #  functions you may want to share. Or some other way, I'm not really sure.
    training_agent = training_agent_tabs()
    model_implementation = model_implementation_tabs()
    results_comparison = results_comparison_tabs()

    with gr.Blocks(theme=gr.themes.Soft()) as app:
        with gr.Tab("Training An Agent"):
            training_agent.render()

        with gr.Tab("Model Implementation"):
            model_implementation.render()

        with gr.Tab("Results Comparison"):
            results_comparison.render()

    app.launch(inbrowser=True)
